spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
    # 非null才返回
  jackson:
    default-property-inclusion: non_null
  mvc:
    path match:
      matching-strategy: ant_path_matcher # springboot2.6之后使用swagger报错


mybatis-plus:
  type-aliases-package: com.t.jk.pojo
  global-config:
    db-config:
      id-type: auto

